spring:
  application:
    name: products-service
  datasource:
    url: jdbc:mysql://${DATA_HOSTNAME:localhost}:3333/ecommerce_products_db?&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATA_USERNAME:davidking}
    password: ${DATA_PASSWORD:davidking!!}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import:
      optional:config-server:http://localhost:8888

  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://config-server:8888
    username: ${CONFIG_SERVER_USR}
    password: ${CONFIG_SERVER_PWD}

server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
---
spring.config.activate.on-profile: docker
spring.cloud.config.uri: http://config-server:8888
